import type { SoundPreset } from '../types'

// ---------------------------------------------------------------------------
// 12 instrument presets. Each maps to a Tone.js synth configuration in
// lib/audio/AudioEngine.ts. ADSR is user-editable from the Sound Engine panel.
// ---------------------------------------------------------------------------

export const SOUND_PRESETS: SoundPreset[] = [
  {
    id: 'dream-piano',
    name: 'Dream Piano',
    description: 'Soft triangle piano with shimmering overtones.',
    kind: 'fm',
    oscillator: 'triangle',
    envelope: { attack: 0.005, decay: 1.6, sustain: 0.25, release: 1.8 },
    modulation: { harmonicity: 3.5, modulationIndex: 6, modulationType: 'sine' },
    gain: 0.9,
    accent: '#60a5fa',
  },
  {
    id: 'neon-ep',
    name: 'Neon EP',
    description: 'Punchy FM electric piano with bell-like attack.',
    kind: 'fm',
    oscillator: 'sine',
    envelope: { attack: 0.002, decay: 0.9, sustain: 0.3, release: 1.1 },
    modulation: { harmonicity: 2, modulationIndex: 12, modulationType: 'sine' },
    gain: 0.85,
    accent: '#c084fc',
  },
  {
    id: 'soft-pad',
    name: 'Soft Pad',
    description: 'Slow-swelling warm pad for ambient textures.',
    kind: 'poly',
    oscillator: 'fatsawtooth',
    envelope: { attack: 0.8, decay: 1.2, sustain: 0.8, release: 2.6 },
    spread: 30,
    gain: 0.55,
    accent: '#818cf8',
  },
  {
    id: 'analog-lead',
    name: 'Analog Lead',
    description: 'Bright detuned saw lead with bite.',
    kind: 'poly',
    oscillator: 'fatsawtooth',
    envelope: { attack: 0.01, decay: 0.2, sustain: 0.7, release: 0.4 },
    spread: 20,
    gain: 0.7,
    accent: '#fb923c',
  },
  {
    id: 'bass-pulse',
    name: 'Bass Pulse',
    description: 'Round square-wave sub bass with tight envelope.',
    kind: 'mono',
    oscillator: 'square',
    envelope: { attack: 0.005, decay: 0.18, sustain: 0.6, release: 0.25 },
    gain: 0.9,
    accent: '#38bdf8',
  },
  {
    id: 'pluck-bell',
    name: 'Pluck Bell',
    description: 'Glassy FM bell with quick metallic decay.',
    kind: 'fm',
    oscillator: 'sine',
    envelope: { attack: 0.001, decay: 1.4, sustain: 0.0, release: 1.2 },
    modulation: { harmonicity: 5.1, modulationIndex: 18, modulationType: 'square' },
    gain: 0.8,
    accent: '#f472b6',
  },
  {
    id: 'lofi-keys',
    name: 'Lo-fi Keys',
    description: 'Mellow triangle keys, slightly detuned and dusty.',
    kind: 'am',
    oscillator: 'triangle',
    envelope: { attack: 0.01, decay: 0.5, sustain: 0.35, release: 0.9 },
    modulation: { harmonicity: 1.5 },
    gain: 0.8,
    accent: '#a78bfa',
  },
  {
    id: 'cyber-choir',
    name: 'Cyber Choir',
    description: 'Vocal-ish stacked sines for synthetic choirs.',
    kind: 'poly',
    oscillator: 'fatsine',
    envelope: { attack: 0.4, decay: 0.8, sustain: 0.9, release: 2.0 },
    spread: 40,
    gain: 0.6,
    accent: '#22d3ee',
  },
  {
    id: 'warm-organ',
    name: 'Warm Organ',
    description: 'Drawbar-style organ with sustained body.',
    kind: 'poly',
    oscillator: 'fatsquare',
    envelope: { attack: 0.01, decay: 0.1, sustain: 1.0, release: 0.3 },
    spread: 14,
    gain: 0.6,
    accent: '#fbbf24',
  },
  {
    id: 'future-marimba',
    name: 'Future Marimba',
    description: 'Percussive FM mallet with woody tone.',
    kind: 'fm',
    oscillator: 'sine',
    envelope: { attack: 0.001, decay: 0.7, sustain: 0.0, release: 0.6 },
    modulation: { harmonicity: 4, modulationIndex: 8, modulationType: 'triangle' },
    gain: 0.85,
    accent: '#34d399',
  },
  {
    id: 'synth-brass',
    name: 'Synth Brass',
    description: 'Bold detuned brass stab with fast swell.',
    kind: 'poly',
    oscillator: 'fatsawtooth',
    envelope: { attack: 0.06, decay: 0.3, sustain: 0.75, release: 0.5 },
    spread: 26,
    gain: 0.65,
    accent: '#f97316',
  },
  {
    id: 'space-arp',
    name: 'Space Arp',
    description: 'Bright square pluck made for delays and arps.',
    kind: 'poly',
    oscillator: 'square',
    envelope: { attack: 0.002, decay: 0.25, sustain: 0.1, release: 0.3 },
    gain: 0.7,
    accent: '#a855f7',
  },
]

export const DEFAULT_PRESET_ID = 'dream-piano'

export function getPreset(id: string): SoundPreset {
  return SOUND_PRESETS.find((p) => p.id === id) ?? SOUND_PRESETS[0]
}
